language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "M9Sg5DIyPuLdL/JE8y1BgvoKwJo8s6WxY+ireT15LDrCd2ziMNFR++Q5xs/4+LML43U7qLe6f/qtTDMd683XFSYzIgu0JvTX78nXHB5BVVnMsZRu6hmqieJ9z0H6v9d8vSZhVvAG8WoofUkpT/NNd76jEUxRayhalbrteKPxsamqx1DX9IQRfEmWwL693/CKyI3alF95MHEahRxYApO7duYhMHkCm1Fw7SJQnssZbv88xXF/OwgC8ApBEacq0ZFukfeyIi/aAbZsOxYSRAlZHKrg5qHAn+HY2l91byrABmE1WtukIr/mXfsShzUrNsARXKiYBgEW39dIMqgzreoL8RNQWqQYHEL9BCTIyEjdCopEpKfcIdy0+rByLqmqbLn7gxSXe80wPT6GWealkCSF9+0ahqWdLErGcX2GTp1UVrmxl4FSlmZc4axOzE+4JsrUEet1NMcvfuX4AUfaKQjfN0XesRAFP9CDUf02eJ0j3jWCQay5Rt1mBANKaLv8wSCdJZc29PIKdULlSvpmZowdxdHR4oPizaXX8BQrxUVKJh/AuYinhHKjGFRQq0CRINm3GBnkWm+KxVtuMpx7tjNigxbImBpX+XKn945lotcBX7PJ5zPLK8BD+l4nSYpK5xG/CGlD10KVE47yIBHHfGbyG803WNhA9VaSpwBSsVb8R8U="
  - secure: "CmZgMx0N+NjeuDr4w07TsWtp72VjRvEskOcMVdLSv4W7X1xEa9uaRIgyVae8HMzHu4wwZg5hDLXSVLUAYObRSLcpOKlIcJBfl/nSoW3+xfVGaeY6kB1bKLUgg22Hdy0FdvShMP1MK9/CoGTHL4toBbSWYRJsINCyC2wHsypMxjn0zionrdBPJXV9BevnuY9uPuN/kS5jhzmMay2end969zyPsg2iRK9KvMOLEpfbnmLNXRtCryWwal4vI/DtT+3FaqAq7LWVJUCUdzGICkzwVJQtz0tyVKcLs2YiubvaVrRA4Mvec73H6kHgRcsniu2JEOBkr7W1bOmtzXrXKDKDXLnfIAvfIVFYUb4j3dJCbpgQfPmEGpd+bmtjOtm+ZNr8R0vJTUkeT/m3hQdTylNJpn3/sUJGECVu6AAboPQ/jJ2j65Gfgrzwe1LkZnOmYy+SbjF86ds9O4W2aBZAFtz5PXUbrA5J7ZD/rI7qgN0fi8HbyBwUH03pEAOATN1IEvdCMC3ybLKimd6LeDbg5eLzco+srqFkz6Dl5yRn4BFYmbJpxzj8rsu6YXSSApRiSsqpx/M2lwxeWEXKsNjyCGIyTAvoweVtO/n6dwm7hiP6mDHUgOPGrNJNPPXb4nHnOtUVOt0eHxfhYb07FTuDUz3g0DtmUDxcI0piWuXKe1eJ3yc="
  - secure: "jN5jkz3i6hizvqjq6p0VLnaZYiMyLsUiQfJBZ2rX8ONnpboyYbxWbFNWFxdPg28zs5ATd9WnWkJHubsIkTVURpqtWaUupyW5NW+j0HatE0gQKrDtTi4vjlP/OBvwtcY2QuQgcT4xSM6/hPPWavrYWuXpSC5zlMcAzCdmJ4P5E/HqToMs3CAKX694rL8sgU2QHrBCAnMoyPGQpFLR8J8npjCxibijh9gTD43tkS7e1VBHiKZh0Om9ITbUa19iPlifPvmxnRmAdYj12N4yHzNXYzmWC9QF+xRQl4tutA4QeGwTzE0XShHnm9q3LEEBE/19MeMJ6LljI5pzJ0zT26E+1cZGr9P/qNv5xZYOF8cpIau/zVzqYsb5ATb/DN+kGJFpPdZI+NOSGPj1b2iMICUKIuQs3tFnLlH49xT/aHBpe6IBTVy+AXwpysVwTpH9i5UOoxmFbCEm9l6F9uXxref+OPBS2A+CNa4yp27YhqlesfeKgqNT9TVGG1ZG+bEz3qHz8XKoPZy6zzH8FVRYg5F4YSRdFb8vesDZkz225sy4V5uQgkkuvsmaFE6V2DTXKDEfqnHBvkXEEsQf+3dHUokcASm9evcJ1+e1/G4u5NzxETnJTIlNuzjFavMPqGD0Cvqt2pJ9V8rNyfhTUx0EBN38GqVr1tM80+/zzGwpO6VOhvg="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_bc82b4744960_key -iv $encrypted_bc82b4744960_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi